### ISSUE TITLE
Avoid exposing API to public

### ISSUE THREAD

**Issue by thedug** [omouse/angular-loggly#2]
Putting your API key in a config file would expose it to the world.

Perhaps using a factory would be more secure?

**Comment by omouse** [comment]
This is a non-issue from what I've seen in the other loggly libraries/code snippets. They're injecting the customer token/API key straight into the client-side JavaScript. I'm assuming that loggly has some infrastructure to throttle logs sent from the same IP or same browser to prevent this kind of attack.
